# environment.yml
name: cctlstm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.*            # mediapipe 需要 <2
  - pandas=2.3.*
  - scikit-learn=1.7.*
  - matplotlib=3.10.*
  - tk                      # tkinter
  - setuptools
  - wheel
  - pip:
    - https://download.pytorch.org/whl/cu121/torch-2.5.1%2Bcu121-cp310-cp310-linux_x86_64.whl
    - torchvision==0.20.1
    - mediapipe==0.10.21
    - opencv-contrib-python==4.11.0.86
    - pillow==11.2.1
    - tqdm==4.67.1
    - pyts==0.13.0
    - vit-pytorch==1.7.7
